[tool.poetry]
name = "mbt"
version = "0.1.0"
description = "My Blob Tool for Azure Blob Storage"
authors = ["agu3rra <agu3rra@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
